In [3]:
import numpy as np

phi_vec = np.array([0.3, 0.4, 0.5])

def hat(vec: np.ndarray) -> np.ndarray:
    """Compute the skew-symmetric matrix (hat operator) of a 3D vector."""
    return np.array([[0, -vec[2], vec[1]],
                     [vec[2], 0, -vec[0]],
                     [-vec[1], vec[0], 0]])

def vee(mat: np.ndarray) -> np.ndarray:
    """Compute the vector (vee operator) from a skew-symmetric matrix."""
    return np.array([mat[2, 1], mat[0, 2], mat[1, 0]])


def rodrigues(mat: np.ndarray) -> np.ndarray:
    """Computer the rotation matrix from a skew-symmetric matrix using Rodrigues' formula."""
    theta = np.linalg.norm(vee(mat))
    if theta < 1e-6:
        return np.eye(3)
    else:
        return np.eye(3) + (np.sin(theta) / theta) * mat + ((1 - np.cos(theta)) / (theta ** 2)) * (mat @ mat)

R1 = rodrigues(hat(phi_vec))
print(R1)

[[ 0.80340057 -0.40182139  0.43941677]
 [ 0.51690398  0.83696633 -0.17971545]
 [-0.29556353  0.37151977  0.8801223 ]]


In [8]:
Rz = rodrigues(hat(np.array([0, 0, phi_vec[2]])))
Ry = rodrigues(hat(np.array([0, phi_vec[1], 0])))
Rx = rodrigues(hat(np.array([phi_vec[0], 0, 0])))
R2 = Rz @ Ry @ Rx
print(R2)

[[ 0.80830707 -0.35701964  0.46816307]
 [ 0.44158016  0.89355941 -0.08098483]
 [-0.38941834  0.27219214  0.87992318]]


In [10]:
print(R1 @ R2.T)  # Should be close to identity matrix

[[ 0.99857119 -0.03987162 -0.03557854]
 [ 0.03486759  0.9906879  -0.13161203]
 [ 0.04049481  0.13018344  0.99066263]]


In [11]:
phi_vec_mini = phi_vec * 0.01
R1_mini = rodrigues(hat(phi_vec_mini))
R2_mini = rodrigues(hat(np.array([0, 0, phi_vec_mini[2]]))) @ \
            rodrigues(hat(np.array([0, phi_vec_mini[1], 0]))) @ \
            rodrigues(hat(np.array([phi_vec_mini[0], 0, 0])))
print(R1_mini @ R2_mini.T)

[[ 1.00000000e+00 -5.97917579e-06 -7.47252428e-06]
 [ 5.97910076e-06  1.00000000e+00 -1.00409463e-05]
 [ 7.47258432e-06  1.00409016e-05  1.00000000e+00]]
